### ISSUE TITLE
水果都跑到屏幕外去了。。。

### ISSUE THREAD

**Issue by cn-qlg** [tangxiangmin/cocos-big-watermelon#1]
![微信截图_20210202141847](https://user-images.githubusercontent.com/15536545/106560221-9f133000-6561-11eb-9ce4-24f5eb0ca031.png)
Win10 Chrome 版本 88.0.4324.104（正式版本） （64 位）

**Comment by cn-qlg** [comment]
另外好像也不支持拖动

**Comment by afuchrisma** [comment]
hahaha

**Comment by tangxiangmin** [comment]
😁 这个应该是cocos发布成web mobile时的问题，把build文件夹下面的index.html上面默认得让oncontextmenu给干掉了，重新发布了一个预览版本，清除缓存重新访问一下就可以

**Comment by net2cn** [comment]
Quick fix: 在默认Canvas节点里勾上Canvas组件的Fit Height和Fit Width之后构建出来的web-mobile版本在PC上水果就不会越界了，项目设置里面可能也要勾上

不启用这两个的话默认它Canvas的width是浏览器窗口的大小（应该跟JavaScript里面用`window.innerWidth`获取到的是一样的，不过我没验证），然后initPhysics的时候获取的width就成了浏览器窗口的width然后物理边界就被设置到跟浏览器窗口一样大了，而不是跟background节点一样大，水果落下之后看起来就像是跑出边框了（实际上并没有，只是物理边界的width变大了没有跟background节点同步而已）

Alternatives: 如果维持原先设定的话（只勾选Fit Height）可以在onLoad的时候让background节点的width跟Canvas的节点width一样，这样看起来就正常了，而不是像现在看起来会跑出边框，哈哈哈哈哈哈（或者initPhysics的时候设置边界用background节点的width和height而不是Canvas的width和height）
